######################################################################
# Automatically generated by qmake (3.1) Wed Sep 9 23:27:34 2020
######################################################################

TEMPLATE = app
TARGET = app
CONFIG += console
DESTDIR = $$PWD/../bin

include($$PWD/../../../PluginFramework.pri)

SOURCES += main.cpp
